apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: kateterport-bff-api
  description: API do BFF da Kateterport
spec:
  type: openapi
  lifecycle: production
  owner: team-name
  definition:
    $text: https://kateterport-bff.sand-fintech.com/swagger/v1/swagger.json
